apiVersion: v1
kind: Service
metadata:
  name: es-client-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    component: es
    role: client
spec:
  selector:
    component: es
    role: client
  ports:
  - name: http
    port: 9200
  type: LoadBalancer