apiVersion: v1
kind: Service
metadata:
  name: es-discovery
  labels:
    component: es-discovery
    role: master
spec:
  selector:
    component: es-discovery
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP