apiVersion: v1
kind: Service
metadata:
  name: es-kibana-service
  labels:
    component: es-kibana-service
spec:
  selector:
    component: es-kibana
  ports:
  - name: http
    port: 80
    targetPort: http
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 108.60.51.1/32